dist: xenial
language: python
python:
    - 2.7
    - 3.6
    
install:
    - pip install -r requirements.travis.txt
    - pip install .

before_script:
    - python travis_call_get_extras.py

script: 
    - pytest
