###############################################################################
# Detector
#
# DESCRIPTION
# The Detector class holds information on the conversion from photons to
# photoelectrons as well as the additional electron noise introduced by the 
# readout electronics and pixel characteristics. These include:
# - saturation, 
# - streaking, 
# - dead pixels and lines
# - detector gaps 
#
# The main noise array is generated by the NGHxRG package and stored on the
# hard-drive for later use. Apparently it takes a long time to generate.
#
#
# Classes:
#  Detector(object)
#
# Methods:
#   
